import type {
  SocietyAccountRow,
  SocietyRow,
  SocietyProfileRow,
  DashboardEvent,
} from "@/lib/supabase/types";

// Mock society
export const mockSociety: SocietyRow = {
  id: "s-001",
  name: "UoM Computer Science Society",
  instagram_handle: "uomcssoc",
  description:
    "The official Computer Science Society at the University of Manchester. Socials, hackathons, tech talks, and career events.",
  bio_url: "https://linktr.ee/uomcssoc",
  university_id: "u-001",
  image_url: null,
  created_at: "2025-09-01T00:00:00Z",
  updated_at: "2026-03-01T00:00:00Z",
};

export const mockProfile: SocietyProfileRow = {
  id: "sp-001",
  society_id: "s-001",
  name: "UoM Computer Science Society",
  handle: "uomcssoc",
  description: mockSociety.description,
  image_url: null,
  follow_count: 482,
  event_count: 23,
  created_at: "2025-09-01T00:00:00Z",
  updated_at: "2026-03-01T00:00:00Z",
};

export const mockAccount: SocietyAccountRow = {
  id: "sa-001",
  auth_user_id: "auth-001",
  society_id: "s-001",
  approval_status: "trusted",
  created_at: "2025-09-01T00:00:00Z",
  updated_at: "2026-03-01T00:00:00Z",
};

// Mock events
export const mockEvents: DashboardEvent[] = [
  {
    id: "e-001",
    title: "Spring Hackathon 2026",
    description:
      "24-hour hackathon open to all UoM students. Build something amazing, win prizes, and meet fellow developers. Food and drinks provided.",
    date: "2026-03-22T09:00:00Z",
    status: "live",
    source: "manual",
    likes: 47,
    attending: 128,
    categories: ["workshop", "social"],
    imageUrl: null,
    registrationUrl: "https://forms.gle/hackathon2026",
    isOnline: false,
    isFree: true,
    price: null,
    schedules: [
      {
        scheduledAt: "2026-03-22T09:00:00Z",
        isEnd: false,
        order: 0,
        locationName: "Kilburn Building",
        locationId: "l-001",
        locationGoogleMapsUrl: "https://maps.google.com/?q=Kilburn+Building+Manchester",
      },
      {
        scheduledAt: "2026-03-23T09:00:00Z",
        isEnd: true,
        order: 1,
        locationName: null,
        locationId: null,
        locationGoogleMapsUrl: null,
      },
    ],
  },
  {
    id: "e-002",
    title: "Tech Talk: AI in Production",
    description:
      "Guest speaker from DeepMind shares practical insights on deploying ML models at scale.",
    date: "2026-03-15T18:00:00Z",
    status: "live",
    source: "scraped",
    likes: 62,
    attending: 89,
    categories: ["academic", "career"],
    imageUrl: null,
    registrationUrl: null,
    isOnline: false,
    isFree: true,
    price: null,
    schedules: [
      {
        scheduledAt: "2026-03-15T18:00:00Z",
        isEnd: false,
        order: 0,
        locationName: "University Place Theatre A",
        locationId: "l-002",
        locationGoogleMapsUrl: null,
      },
      {
        scheduledAt: "2026-03-15T20:00:00Z",
        isEnd: true,
        order: 1,
        locationName: null,
        locationId: null,
        locationGoogleMapsUrl: null,
      },
    ],
  },
  {
    id: "e-003",
    title: "CSS Pub Quiz Night",
    description:
      "Test your knowledge of tech trivia, pop culture, and CS fundamentals. Teams of 4-6. Prizes for top 3!",
    date: "2026-03-12T19:30:00Z",
    status: "live",
    source: "scraped",
    likes: 34,
    attending: 56,
    categories: ["social"],
    imageUrl: null,
    registrationUrl: null,
    isOnline: false,
    isFree: true,
    price: null,
    schedules: [
      {
        scheduledAt: "2026-03-12T19:30:00Z",
        isEnd: false,
        order: 0,
        locationName: "256 Wilmslow Road",
        locationId: "l-003",
        locationGoogleMapsUrl: null,
      },
    ],
  },
  {
    id: "e-004",
    title: "CV Workshop with Bloomberg",
    description:
      "Get your CV reviewed by Bloomberg engineers. Bring a printed copy. Limited to 30 attendees.",
    date: "2026-03-28T14:00:00Z",
    status: "ingested",
    source: "manual",
    likes: 18,
    attending: 27,
    categories: ["career", "workshop"],
    imageUrl: null,
    registrationUrl: "https://forms.gle/cv-workshop",
    isOnline: false,
    isFree: true,
    price: null,
    schedules: [
      {
        scheduledAt: "2026-03-28T14:00:00Z",
        isEnd: false,
        order: 0,
        locationName: "Kilburn Building LF15",
        locationId: "l-004",
        locationGoogleMapsUrl: null,
      },
      {
        scheduledAt: "2026-03-28T16:00:00Z",
        isEnd: true,
        order: 1,
        locationName: null,
        locationId: null,
        locationGoogleMapsUrl: null,
      },
    ],
  },
  {
    id: "e-005",
    title: "Introduction to Rust",
    description:
      "Beginner-friendly workshop on the Rust programming language. Laptops required.",
    date: "2026-04-02T17:00:00Z",
    status: "live",
    source: "manual",
    likes: 29,
    attending: 41,
    categories: ["workshop", "academic"],
    imageUrl: null,
    registrationUrl: null,
    isOnline: false,
    isFree: true,
    price: null,
    schedules: [
      {
        scheduledAt: "2026-04-02T17:00:00Z",
        isEnd: false,
        order: 0,
        locationName: "Kilburn Building LF31",
        locationId: "l-005",
        locationGoogleMapsUrl: null,
      },
      {
        scheduledAt: "2026-04-02T19:00:00Z",
        isEnd: true,
        order: 1,
        locationName: null,
        locationId: null,
        locationGoogleMapsUrl: null,
      },
    ],
  },
  {
    id: "e-006",
    title: "End of Year Ball",
    description:
      "Celebrate the end of the academic year with a formal dinner, live DJ, and awards ceremony.",
    date: "2026-05-10T19:00:00Z",
    status: "live",
    source: "scraped",
    likes: 91,
    attending: 203,
    categories: ["social"],
    imageUrl: null,
    registrationUrl: "https://fixr.co/event/css-ball",
    isOnline: false,
    isFree: false,
    price: "£35",
    schedules: [
      {
        scheduledAt: "2026-05-10T19:00:00Z",
        isEnd: false,
        order: 0,
        locationName: "Kimpton Clocktower Hotel",
        locationId: "l-006",
        locationGoogleMapsUrl: "https://maps.google.com/?q=Kimpton+Clocktower+Manchester",
      },
      {
        scheduledAt: "2026-05-11T01:00:00Z",
        isEnd: true,
        order: 1,
        locationName: null,
        locationId: null,
        locationGoogleMapsUrl: null,
      },
    ],
  },
  {
    id: "e-007",
    title: "Competitive Programming Contest",
    description:
      "Monthly competitive programming session. Solve algorithmic challenges on LeetCode/Codeforces.",
    date: "2026-03-08T14:00:00Z",
    status: "live",
    source: "scraped",
    likes: 15,
    attending: 22,
    categories: ["academic"],
    imageUrl: null,
    registrationUrl: null,
    isOnline: true,
    isFree: true,
    price: null,
    schedules: [
      {
        scheduledAt: "2026-03-08T14:00:00Z",
        isEnd: false,
        order: 0,
        locationName: null,
        locationId: null,
        locationGoogleMapsUrl: null,
      },
      {
        scheduledAt: "2026-03-08T17:00:00Z",
        isEnd: true,
        order: 1,
        locationName: null,
        locationId: null,
        locationGoogleMapsUrl: null,
      },
    ],
  },
  {
    id: "e-008",
    title: "Women in Tech Panel",
    description:
      "A panel discussion with women leaders in tech from Manchester's tech scene. Q&A session included.",
    date: "2026-03-20T17:30:00Z",
    status: "live",
    source: "manual",
    likes: 53,
    attending: 74,
    categories: ["career", "social"],
    imageUrl: null,
    registrationUrl: null,
    isOnline: false,
    isFree: true,
    price: null,
    schedules: [
      {
        scheduledAt: "2026-03-20T17:30:00Z",
        isEnd: false,
        order: 0,
        locationName: "Alan Turing Building",
        locationId: "l-007",
        locationGoogleMapsUrl: null,
      },
      {
        scheduledAt: "2026-03-20T19:30:00Z",
        isEnd: true,
        order: 1,
        locationName: null,
        locationId: null,
        locationGoogleMapsUrl: null,
      },
    ],
  },
];

export const mockCategories = [
  { id: "cat-001", name: "social" },
  { id: "cat-002", name: "academic" },
  { id: "cat-003", name: "sports" },
  { id: "cat-004", name: "arts" },
  { id: "cat-005", name: "career" },
  { id: "cat-006", name: "workshop" },
  { id: "cat-007", name: "trip" },
];

export const mockUniversities = [
  { id: "u-001", name: "University of Manchester" },
  { id: "u-002", name: "Manchester Metropolitan University" },
  { id: "u-003", name: "University of Salford" },
];
